name: bump me

on:
  pull_request:
    branches: ["master"]
    types: ["closed"]

jobs:
  BumpVersion:
    name: Bump version
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-20.04
    container:
      image: python:3.7-alpine
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      BUMPER_TOKEN: ${{ secrets.BUMPER_TOKEN }}
    steps:
      - name: Install git and bash
        run: |
          apk add git bash
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Install bump
        run : |
          pip install bump
      - name: Check package version
        run: |
          bash utils/versioning/bump_version.sh
